### ISSUE TITLE
Any way to match on "reflection equality"?

### ISSUE THREAD

**Issue by rquinlivan** [bguthrie/shrubbery#11]
Is there a way to use shrubbery's matchers in a way that is equivalent to Mockito's `refeq()` matcher? This can be useful when testing Clojure code that must use Java interop to create object instances.

For example, in my function I have to construct a `java.util.ArrayList` to pass to an underlying Java library. I want to assert that the contents of the `ArrayList` created inline in the function are equivalent (but not object-identical) to the contents of the vec I use to call it.

```clojure
(defn subscribe! [kafka-consumer topic]
  (let [topics (doto (new ArrayList) (.add topic))]
    (log/info "Subscribing on topic" topic)
    (.subscribe kafka-consumer topics)))

;; test
(deftest test-subscribe!
  (testing "Calling subscribe! calls the #subscribe method on the underlying consumer"
    (let [kafka-consumer (spy mock-consumer)
          topics-vec ["a-topic"]
          topics-list (doto (new ArrayList) (.add "a-topic"))]
      (module/subscribe! kafka-consumer topics-vec)
      (is (received? kafka-consumer subscribe (ref-eq topics-list))))))
```

**Comment by bguthrie** [comment]
Sorry for the slight delay. Ten months to respond! How's that for an open-source SLA?

Hopefully by now you've figured out that `received?` (and under the covers, `call-count`) expect a vector of args to check against, rather than a unitary arg. Apologies for the confusion! I went back and forth about whether to raise in this case or simply coerce to a vector, and rather than  perpetuate the confusion I opted for the latter in the attached pull request. (A full spec conversion may be in my future.) If you have any feedback on the change, I'd welcome it.
